### ISSUE TITLE
Question: Is there a way to set BS style(classes) for search gadget?

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#655]
I want the search to be in the BS style.
Now I can only do it with JS.

Something like
```
$(document).ready(function(){
		$('.gpArea_Search div').addClass('input-group');
		$('.gpArea_Search .text').addClass('form-control');
		$('.gpArea_Search .submit').addClass('input-group-append btn btn-primary');
		
		$('.filetype-special_search form').addClass('input-group');
		$('.filetype-special_search .text').addClass('form-control');
		$('.filetype-special_search .submit').addClass('input-group-append btn btn-primary');
		
	});
```

It basically works, but the negative side is a delayed restyling. Is there another way to solve this task?

![image](https://user-images.githubusercontent.com/14929385/87569787-516fcc80-c6d0-11ea-8193-460c5364654a.png)

![image](https://user-images.githubusercontent.com/14929385/87569690-2dac8680-c6d0-11ea-80a2-f98760bcdc1d.png)

**Comment by juek** [comment]
The BS4 theme I'm working on does it using @extend
It will be up soon, it's almost ready.

Here is a Scss code snippet

// 'Bootstrapify' Typesetter's built-in search form and -results

```scss
.filetype-special_search.search_results {
  h2 {
    @extend .h3;
  }
  form {
    @extend .input-group;
    max-width: 24rem;
    margin-bottom: 1rem;
    input.text {
      @extend .form-control;
      border-top-right-radius: 0;
      border-bottom-right-radius: 0;
      border-right: none;
    }
    input.submit {
      @extend .btn, .btn-secondary;
      border-top-left-radius: 0;
      border-bottom-left-radius: 0;
    }
  }
  p {
    @extend .alert, .alert-secondary;
  }
  .result_list {
    margin-bottom: 1.5rem;
    div {
      h4 {
        @extend .h5;
        margin-bottom: 0.33rem;
      }
      margin: 0.75rem 0;
    }
  }
  .pagination .page-link {
    // needs to overrule additional.css by specificity
    padding: $pagination-padding-y $pagination-padding-x;
  }
}
```
