### ISSUE TITLE
Do not show Bootstrap_Dropdown_Divider in SiteMap

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#667]
What is the best way to hide Bootstrap_Dropdown_Divider from SiteMap? Can we mark this extra as "noindex"? Or should we explicitly exclude it in map.php?

![image](https://user-images.githubusercontent.com/14929385/90955896-4277f900-e48a-11ea-9740-eda2f3392222.png)

**Comment by juek** [comment]
Use 'Menu Output - Classes' on extra content items in Page Manager is now fixed with https://github.com/Typesetter/Typesetter/commit/290c5ca6b33eba282b48cc0f439b7f0c05a0c6fe

```
.filetype-special_sitemap .hide-in-sitemap {
  dislplay: none;
}
```

Should work now.

**Comment by mahotilo** [comment]
Yes, it works.

Pity that we cannot integrate all these adjustments into extra itself:)

**Comment by juek** [comment]
> Pity that we cannot integrate all these adjustments into extra itself

It's really a special case, that could also be solved much more elegant - without an extra area. E.g. by assigning a menu item class 'dropdown-divider-before' and use only css to style that item like

```css
.dropdown-menu > li.dropdown-divider-before {
  margin-top: $dropdown-divider-margin-y;
  padding-top: $dropdown-divider-margin-y;
  border-top: 1px solid $dropdown-divider-bg
}
```

In fact I only added the 'Bootstrap Dropdown Divider' area to show a practical use case for an extra content area in a menu. I myself woldn't neccessarily use it but rather go for the above mentioned solution.
